---
checks:
  addAllBuiltIn: true
  execlude:
    - "default-service-account"
    - "no-anti-affinity"
    - "required-annotation-email"
    - "required-label-owner"
    - "unset-cpu-requirements"
    - "unset-memory-requirements"
