## Vanilla Test
tests:
  - name: "me"
    vanilla: true
    secret: true
    test: |
      test_name: Make sure cookie is required to log in

      includes:
        - !include common.yaml

      stages:
        - name: Try to check user info without login information
          request:
            url: "{host}/userinfo"
            method: GET
          response:
            status_code: 401
            json:
              error: "no login information"
            headers:
              content-type: application/json

        - name: login
          request:
            url: "{host}/login"
            json:
              user: test-user
              password: correct-password
            method: POST
            headers:
              content-type: application/json
          response:
            status_code: 200
            cookies:
              - session-cookie
            headers:
              content-type: application/json

        - name: Check user info
          request:
            url: "{host}/userinfo"
            method: GET
          response:
            status_code: 200
            json:
              name: test-user
            headers:
              content-type: application/json








#
# Simple Test Suite
# Does not use Test Suite Template, but Stage Template
#
#  Test Suite Name
#  tests[0].name -- Test Suite Name
#  - name: "Sample Suite"
#
#  Stores Test Suite in Secret instead of configmap
#  tests[0].secret -- Test Suite Secret
#    secret: true
#
#  Test Suite Values
#  tests[0].values -- Go Sprig Values accessible under `$.tavern` for the entire Suite
#    values:
#      enable_products: true
#
#  Tavern Test Suite Definition
#
#
#    test:
#      stages:
#
#        ## Straight Test
#        - name: "Try to get user"
#          stage:
#            request:
#              url: "{host}/users/joebloggs"
#              method: GET
#              json:
#                clusterName: "test"
#            response:
#              status_code:
#                - 200
#                - 404
