
{{- if $.Values.cronjob.enabled }}
apiVersion: {{ default "batch/v1beta1" $.Values.cronjob.apiVersion }}
kind: CronJob
metadata:
  name: {{ include "lib.utils.fullname" $ }}
  labels: {{- include "lib.utils.labels" $ | nindent 4 }}
spec:
  schedule: {{ $.Values.cronjob.schedule }}
  {{- if and $.Values.cronjob.conf (kindIs "map" $.Values.cronjob.conf) -}}
    {{- toYaml $.Values.cronjob.conf | nindent 2 }}
  {{- end }}
  jobTemplate: {{- include "tavern.job" $ | nindent 4 }}
{{- else }}
apiVersion: {{ default "batch/v1" $.Values.job.apiVersion }}
kind: Job
metadata:
  name: {{ include "lib.utils.fullname" $ }}
  labels: {{- include "lib.utils.labels" $ | nindent 4 }}
  {{- include "tavern.job" $ | nindent 0 }}
{{- end }}

{{- define "tavern.job" }}
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: OnFailure

      volumes:





  backoffLimit: 4






{{- end }}
