

{{- if $.Values.cronjob.enabled }}
apiVersion: {{ default "batch/v1beta1" $.Values.cronjob.apiVersion }}
kind: CronJob
metadata:
  name: {{ include "lib.utils.fullname" $ }}
  labels: {{- include "lib.utils.labels" $ | nindent 4 }}
spec:
  schedule: {{ $.Values.cronjob.schedule }}
  {{- if and $.Values.cronjob.conf (kindIs "map" $.Values.cronjob.conf) -}}
    {{- toYaml $.Values.cronjob.conf | nindent 2 }}
  {{- end }}
  jobTemplate: {{- include "tavern.job" $ | nindent 4 }}
{{- else }}
apiVersion: {{ default "batch/v1" $.Values.job.apiVersion }}
kind: Job
metadata:
  name: {{ include "lib.utils.fullname" $ }}
  labels: {{- include "lib.utils.labels" $ | nindent 4 }}
  {{- include "tavern.job" $ | nindent 0 }}
{{- end }}

{{- define "tavern.job" }}
{{- $tavern_tests := (fromYaml (include "tavern.tests" $)) -}}
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: tavern
        image: bash
        command:
          - cat
          - /tests/*.yaml

    {{- if or $tavern_tests.tests $.Values.volumeMounts }}
        volumeMounts:
      {{- if $.Values.volumeMounts }}
        {{- toYaml $.Values.volumeMounts | nindent 10 }}
      {{- end }}
      {{- if $tavern_tests.tests }}
        {{- range $tavern_tests.tests }}
          - name: {{ include "lib.utils.fullname" (dict "name" .name "context" $) }}
            mountPath: /tests/{{ .name }}_test.yaml
            subPath: {{ .name }}_test.yaml
        {{- end }}
      {{- end }}
    {{- end }}
    {{- if or $tavern_tests.tests $.Values.volumes }}
      volumes:
      {{- if $tavern_tests.tests }}
        {{- range $tavern_tests.tests }}
          {{- $ref := include "lib.utils.fullname" (dict "name" .name "context" $) }}
          {{- if .secret }}
        - name: {{ $ref }}
          secret:
            secretName: {{ $ref }}
          {{- else }}
        - name: {{ $ref }}
          configMap:
            name: {{ $ref }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- if $.Values.volumes }}
        {{- toYaml $.Values.volumes | nindent 4 }}
      {{- end }}
    {{- end }}
{{- end }}
