{{- $tavern_tests := (fromYaml (include "tavern.tests" $)) }}
{{- if $tavern_tests.tests }}
  {{- range $tavern_tests.tests }}
---
kind: "ConfigMap"
apiVersion: "v1"
metadata:
  name: "test"
data:
  {{ .test_name }}_test.yaml: | {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
