apiVersion: v2
name: csgo
description: Source Server
type: application
version: 0.1.0
appVersion: 1.16.0
dependencies:
  - name: "library"
    version: 0.2.0
    repository: https://buttahtoast.github.io/helm-charts/
maintainers:
  - name: oliverbaehler
    email: oliverbaehler@hotmail.com
