{{- $config := $.Values.config }}
{{- if or (and $config.rcon_password (kindIs "string" $config.rcon_password)) (and $config.password (kindIs "string" $config.password)) (and $config.workshop.auth (kindIs "string" $config.workshop.auth)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lib.utils.common.fullname" $ }}-config
  labels: {{- include "lib.utils.common.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- if and $config.rcon_password (kindIs "string" $config.rcon_password) }}
  SRCDS_RCONPW: {{ $config.rcon_password | b64enc }}
  {{- end }}
  {{- if and $config.password (kindIs "string" $config.password) }}
  SRCDS_PW: {{ $config.password | b64enc }}
  {{- end }}
  {{- if and $config.workshop.auth (kindIs "string" $config.workshop.auth) }}
  SRCDS_WORKSHOP_AUTHKEY: {{ $config.password | b64enc }}
  {{- end }}
{{- end }}
