apiVersion: v1
kind: Service
metadata:
  name: {{ include "lib.utils.fullname" $ }}
  labels: {{- include "lib.utils.labels" $ | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "lib.utils.selectorLabels" $ | nindent 4 }}
