apiVersion: v2
name: tavern
description: "Unofficial Tavern Helm Chart"
type: application
version: 0.3.0
appVersion: 1.1.0
home: "https://tavern.readthedocs.io/en/latest/"
icon: "https://tavern.readthedocs.io/en/latest/_static/icon.png"
keywords:
  - python
  - tavern
  - API testing
  - pytest
dependencies:
 - name: manifests
   version: ">= 0.4.0 < 1.0.0"
   repository: https://bedag.github.io/helm-charts
maintainers:
  - name: oliverbaehler
    email: oliverbaehler@hotmail.com
  - name: chifu1234
    email: kk@sudo-i.net
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/prerelease: "true"
  artifacthub.io/images: |
    - name: tavern
      image: buttahtoast/docker-tavern:1.0.4
