apiVersion: v2
name: tavern
description: "Unofficial Tavern Helm Chart"
type: application
version: 0.1.0
appVersion: 1.0.3
home: "https://tavern.readthedocs.io/en/latest/"
icon: "https://tavern.readthedocs.io/en/latest/_static/icon.png"
keywords:
  - python
  - tavern
  - API testing
  - pytest
dependencies:
  - name: "library"
    version: 0.2.0
    repository: https://buttahtoast.github.io/helm-charts/
maintainers:
  - name: oliverbaehler
    email: oliverbaehler@hotmail.com
