---
name: 'PR Labels'
on: 
  pull_request_target:
    types: [opened, synchronize, reopened]
jobs:
  size-label:
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: pascalgn/size-label-action@be08a2d5f857dc99c5b9426cdb5a8ea1aa7f0399
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
